package parser

// Magic Numbers for Target Index TLV
const (
	TRACK_INDEX_WEAK_SNR = 253 // Point not associated, SNR too weak
	TRACK_INDEX_BOUNDS   = 254 // Point not associated, located outside boundary of interest
	TRACK_INDEX_NOISE    = 255 // Point not associated, considered as noise
)

// Defined TLV's
const (
	DETECTED_POINTS                  = 1
	RANGE_PROFILE                    = 2
	NOISE_PROFILE                    = 3
	AZIMUT_STATIC_HEAT_MAP           = 4
	RANGE_DOPPLER_HEAT_MAP           = 5
	STATS                            = 6
	DETECTED_POINTS_SIDE_INFO        = 7
	AZIMUT_ELEVATION_STATIC_HEAT_MAP = 8
	TEMPERATURE_STATS                = 9

	// xWRL6432 Out-of-box demo packets
	EXT_DETECTED_POINTS              = 301
	EXT_RANGE_PROFILE_MAJOR          = 302
	EXT_RANGE_PROFILE_MINOR          = 303
	EXT_RANGE_AZIMUT_HEAT_MAP_MAJOR  = 304
	EXT_RANGE_AZIMUT_HEAT_MAP_MINOR  = 305
	EXT_STATS                        = 306
	EXT_PRESENCE_INFO                = 307
	EXT_TARGET_LIST                  = 308
	EXT_TARGET_INDEX                 = 309
	EXT_MICRO_DOPPLER_RAW_DATA       = 310
	EXT_MICRO_DOPPLER_FEATURES       = 311
	EXT_RADAR_CUBE_MAJOR             = 312
	EXT_RADAR_CUBE_MINOR             = 313
	EXT_POINT_CLOUD_INDICES          = 314
	EXT_ENHANCED_PRESENCE_INDICATION = 315
	EXT_ADC_SAMPLES                  = 316
	EXT_CLASSIFIER_INFO              = 317
	EXT_RX_CHAN_COMPENSATION_INFO    = 318
	EXT_QUICK_EVAL_INFO              = 319
	EXT_POINT_CLOUD_ANTENNA_SYMBOLS  = 320

	GESTURE_FEATURES_6432        = 350
	GESTURE_CLASSIFIER_6432      = 351
	GESTURE_PRESENCE_x432        = 352
	GESTURE_PRESENCE_THRESH_x432 = 353
	EXT_MAGNITUDE                = 354
	EXT_RANGEIDX                 = 355
	EXT_ELEVIDX                  = 356
	EXT_AZIMIDX                  = 357
	EXT_POINT_CLOUD_CARTESIAN    = 360
	EXT_POINT_CLOUD_SPHERICAL    = 361
	EXT_POINT_CLOUD_MINOR        = 362
	EXT_RANGE_DOPPLER_MAP        = 363
	EXT_CLASSIFIER_VARS          = 364

	SPHERICAL_POINTS           = 1000
	TRACKERPROC_3D_TARGET_LIST = 1010
	TRACKERPROC_TARGET_INDEX   = 1011
	TRACKERPROC_TARGET_HEIGHT  = 1012
	COMPRESSED_POINTS          = 1020
	PRESCENCE_INDICATION       = 1021 // TODO: typo?
	OCCUPANCY_STATE_MACHINE    = 1030
	SURFACE_CLASSIFICATION     = 1031
	EXT_VELOCITY               = 1033
	EXT_STATS_BSD              = 1034
	EXT_TARGET_LIST_2D_BSD     = 1035

	VITALSIGNS = 1040

	GESTURE_FEATURES_6843    = 1050
	GESTURE_OUTPUT_PROB_6843 = 1051

	EXT_MODE_SWITCH_INFO  = 1060
	EXT_CAMERA_ON_IND     = 1061
	EXT_CLUSTER_LOCATIONS = 1062

	EXT_CAM_TRIGGERS = 3000

	// BAC SPECIFIC TLV
	INTRUSION_DET_INFO       = 12
	INTRUSION_DET_3D_DET_MAT = 13
	INTRUSION_DET_3D_SNR     = 14

	POINT_CLOUD                  = 1020
	OCCUPANCY_FEATURES           = 1040
	OCCUPANCY_CLASSIFICATION_RES = 1041
	OCCUPANCY_HEIGHT_RES         = 1042

	DEBUG_ANT_GEOMETRY               = 2000
	DEBUG_DET_MAT_ANGLE_SLICE        = 2001
	DEBUG_SNR_MAT_ANGLE_SLICE        = 2002
	DEBUG_CAPON_HEATMAP              = 2003
	DEBUG_CAPON_RAW_CFAR_POINT_CLOUD = 2004
	DEBUG_CAPON_FFT_HEATMAP          = 2006
	DEBUG_RADAR_CUBE_FRESH_CHUNK     = 2007
)
